### ISSUE TITLE
Application Icons

### ISSUE THREAD

**Issue by nazoge** [identmous/identmous#2]
アイコン作成

**Comment by nazoge** [comment]
匿名の身元なのでロックされてる家とか人間とかを想像中

**Comment by nazoge** [comment]
水平思考（問題解決のためには自由な発想でアイデアを生み出す考え）の考え方でこのSNSを使ってほしいと思い水平思考ゲームといえばウミガメのスープなのでかめを描きました
![1668488181247.jpg](https://user-images.githubusercontent.com/70749085/201830458-7136c230-f568-416c-9450-69dd5381246f.jpg)

**Comment by nazoge** [comment]
![Screenshot_2022-11-15-14-03-23-943-edit_com.teslacoilsw.launcher.jpg](https://user-images.githubusercontent.com/70749085/201830843-867098e3-288b-42ce-afe1-e93199ed9e61.jpg)

**Comment by yuimarudev** [comment]
> ![Screenshot_2022-11-15-14-03-23-943-edit_com.teslacoilsw.launcher.jpg](https://user-images.githubusercontent.com/70749085/201830843-867098e3-288b-42ce-afe1-e93199ed9e61.jpg)

いいね

**Comment by yuimarudev** [comment]
> 水平思考（問題解決のためには自由な発想でアイデアを生み出す考え）の考え方でこのSNSを使ってほしいと思い水平思考ゲームといえばウミガメのスープなのでかめを描きました ![1668488181247.jpg](https://user-images.githubusercontent.com/70749085/201830458-7136c230-f568-416c-9450-69dd5381246f.jpg)

うお〜　水平思考
